name: push to production database
on: push
    branches:
      - main

jobs:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npx prisma migrate deploy
